name: CI

on:
  push:
    branches:
      - main
      - 'pr/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build

  deploy:
    name: Deploy (Firebase Hosting)
    needs: build
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Firebase Hosting
        if: github.ref == 'refs/heads/main' && env.FIREBASE_TOKEN != ''
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUGETJUKOV }}
          projectId: bugetjukov
          channelId: live
